### ISSUE TITLE
possible to specify database id?

### ISSUE THREAD

**Issue by selfagency** [inthepocket/itp-express-redis-cache#2]
this seems to put the cache in db 0. i'd like it to be in a different db. how can i change it?

**Comment by jonathandemoor** [comment]
Hi @selfagency,

Currently it isn't possible to pass through this option, but feel free to make a pull request 😉

When creating a new redis client you also can specify a db option.

[https://github.com/inthepocket/itp-express-redis-cache/blob/36967283556b7da825fa2ff4a671633127b91f00/lib/ITPExpressRedisCache.js#L86](https://github.com/inthepocket/itp-express-redis-cache/blob/36967283556b7da825fa2ff4a671633127b91f00/lib/ITPExpressRedisCache.js#L86)


> DB: If set, client will run Redis select command on connect.
> [https://github.com/NodeRedis/node_redis#rediscreateclient](https://github.com/NodeRedis/node_redis#rediscreateclient)

```
const db = options.db || process.env.REDIS_DB || 0;

this.redisClient = require('redis').createClient(
      port,
      host,
      { auth_pass: authPass },
      db
 );
```
